# 外部配置打开
logging.config: ./logback.xml
#业务日期
mock.date: "2024-05-11"

  #模拟数据发送模式
mock.type: "kafka"
  #http模式下，发送的地址
mock.url: "http://localhost:8081/gmall_logger/log"

mock:
  kafka-server: "hadoop102:9092,hadoop103:9092,hadoop104:9092"
  kafka-topic: "base_log"

  #最大条数
mock.startup.count: 1000000
  #设备最大值
mock.max.mid: 100
  #会员最大值
mock.max.uid: 1000
  #商品最大值
mock.max.sku-id: 1000
  #页面平均访问时间
mock.page.during-time-ms: 20000
  #错误概率 百分比
mock.error.rate: 3
  #每条日志发送延迟 ms
mock.log.sleep: 500
  #商品详情来源  用户查询，商品推广，智能推荐, 促销活动
mock.detail.source-type-rate: "40:25:15:20"

  #领取购物券概率
mock.if_get_coupon_rate: 75

  #购物券最大id
mock.max.coupon-id: 3

  #搜索关键词
mock.search.keyword: "图书,小米,iphone11,电视,口红,ps5,苹果手机,小米盒子"

  #是否产生倾斜数据: 1是、0否;目前是 mid、uid、skuid(商品明细) 产生倾斜
mock.data-skew: 0
  #倾斜比率，百分比
mock.skew-rate: 80
